export const GENRE_EMOJIS: Record<string, string> = {
  Fiction: "📖",
  Fantasy: "🐉",
  Audiobook: "🎧",
  "Science Fiction": "🚀",
  "Science Fiction Fantasy": "🌌",
  Classics: "📜",
  Adult: "🔖",
  Nonfiction: "📚",
  Adventure: "🗺️",
  "Young Adult": "⭐",
  Novels: "📗",
  Romance: "💕",
  "High Fantasy": "⚔️",
  Magic: "✨",
  Mystery: "🔍",
  Horror: "👻",
  Thriller: "⚡",
  "Book Club": "👥",
  "Epic Fantasy": "🗡️",
  Literature: "🖋️",
  Contemporary: "🌆",
  "Historical Fiction": "🏰",
  Historical: "🕰️",
  History: "🏛️",
  "Graphic Novels": "🎨",
  Comics: "💬",
  Childrens: "🎈",
  Dystopia: "🔋",
  "Speculative Fiction": "🔮",
  "Short Stories": "📝",
  Crime: "🕵️",
  Science: "🔬",
  Paranormal: "👁️",
  "Space Opera": "🌠",
  Philosophy: "🤔",
  Space: "🌌",
  Psychology: "🧠",
  Humor: "😂",
  "Self Help": "💪",
  "Mystery Thriller": "🔪",
  War: "⚔️",
  Business: "💼",
  Suspense: "😰",
  "Dark Fantasy": "🌑",
  Biography: "👤",
  "Graphic Novels Comics": "🎭",
  Dragons: "🐲",
  Epic: "⚡",
  "Middle Grade": "🎒",
  Memoir: "📔",
  Politics: "🏛️",
  "Urban Fantasy": "🌃",
  "Personal Development": "🌱",
  "Literary Fiction": "✍️",
  Mythology: "🏺",
  "Post Apocalyptic": "☢️",
  Supernatural: "🌀",
  Aliens: "👽",
  Reference: "📖",
  "Military Fiction": "🎖️",
};

export function getEmoji(genre: string): string {
  return GENRE_EMOJIS[genre] ?? "📕";
}
