/// <reference types="bun" />

/**
 * Rebuilds the vendored `boko` WASM module in `vendor/boko/`.
 *
 * The build is checked in deliberately: a clone has no Rust toolchain and CI
 * compiles nothing. Run this only to bump the version, then commit the result.
 *
 *   bun run build:boko              # rebuild at BOKO_VERSION below
 *   bun run build:boko 0.6.0        # bump, then commit vendor/boko/
 *
 * **boko is GPL-3.0-or-later and BookHive is MIT.** Linking it into our own
 * process makes the distributed artifact a combined work (see
 * `src/services/convertToEpub.ts` and AGENTS.md), so this script also keeps
 * two GPL obligations automatic: `LICENSE` ships alongside the binary (§4),
 * and `manifest.json` records the corresponding-source commit (§6).
 *
 * Both must reach the *image*, not just the repo — only `.output/` is copied
 * into it, so `vite.config.ts` emits them next to `boko_bg.wasm` as
 * `boko.LICENSE` / `boko.manifest.json`.
 */
import { execFileSync } from "node:child_process";
import { copyFileSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

/** Single source of truth for the vendored version. Override with argv[2]. */
const BOKO_VERSION = "0.5.0";

const version = process.argv[2] ?? BOKO_VERSION;
const repoRoot = path.resolve(import.meta.dir, "..");
const vendorDir = path.join(repoRoot, "vendor", "boko");

/**
 * What gets vendored. `package.json` is skipped (imported by path, not
 * package name), and so is wasm-pack's `.gitignore` — it's a single `*`,
 * which would exclude this whole directory from git.
 */
const ARTIFACTS = ["boko.js", "boko.d.ts", "boko_bg.wasm", "boko_bg.wasm.d.ts", "LICENSE"];

function run(cmd: string, args: string[], cwd?: string): string {
  return execFileSync(cmd, args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] });
}

function require_(cmd: string, install: string): void {
  try {
    run(cmd, ["--version"]);
  } catch {
    console.error(`✗ \`${cmd}\` not found. Install it with:\n    ${install}`);
    process.exit(1);
  }
}

require_("cargo", "https://rustup.rs");
require_("wasm-pack", "cargo install wasm-pack");

const work = mkdtempSync(path.join(tmpdir(), "boko-build-"));
const src = path.join(work, "src");
const pkg = path.join(work, "pkg");

try {
  console.log(`→ cloning boko v${version}`);
  run("git", [
    "clone",
    "--depth",
    "1",
    "--branch",
    `v${version}`,
    "https://github.com/zacharydenton/boko",
    src,
  ]);
  // Full SHA, not abbreviated — this is what a Corresponding Source request gets answered with.
  const commit = run("git", ["rev-parse", "HEAD"], src).trim();

  console.log(`→ building wasm (${commit}) — a couple of minutes on a cold cargo cache`);
  // `--target nodejs` loads the wasm synchronously with no fetch/top-level await,
  // which is what lets the bundled worker load it. `--no-default-features` drops
  // CLI-only deps that don't build for wasm32.
  run(
    "wasm-pack",
    [
      "build",
      "--release",
      "--target",
      "nodejs",
      "--out-dir",
      pkg,
      "--",
      "--no-default-features",
      "--features",
      "wasm",
    ],
    src,
  );

  mkdirSync(vendorDir, { recursive: true });
  for (const file of ARTIFACTS) {
    copyFileSync(path.join(pkg, file), path.join(vendorDir, file));
  }
  writeFileSync(
    path.join(vendorDir, "manifest.json"),
    `${JSON.stringify(
      {
        _comment:
          "Generated by scripts/build-boko-wasm.ts. Do not edit by hand; run `bun run build:boko`.",
        name: "boko",
        version,
        commit,
        license: "GPL-3.0-or-later",
        licenseFile: "LICENSE",
        upstream: "https://github.com/zacharydenton/boko",
        target: "nodejs",
        buildCommand:
          "wasm-pack build --release --target nodejs -- --no-default-features --features wasm",
        correspondingSource: `Complete corresponding source for boko_bg.wasm is the tree at https://github.com/zacharydenton/boko commit ${commit} (tag v${version}), built with the command in \`buildCommand\`. It is also available on written request for as long as this binary is distributed.`,
      },
      null,
      2,
    )}\n`,
  );

  const wasmKb = Math.round(Bun.file(path.join(vendorDir, "boko_bg.wasm")).size / 1024);
  console.log(`✓ vendor/boko updated to v${version} (${commit}), ${wasmKb} KB wasm`);
  console.log("  next: bun test src/services/convertToEpub.test.ts && git add vendor/boko");
} finally {
  rmSync(work, { recursive: true, force: true });
}
